[project]
name = "htmx-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.128.5",
    "jinja2>=3.1.4",
    "python-multipart>=0.0.9",
    "uvicorn>=0.30.6",
    "websockets>=12.0",
]
